import{a as u,S as v,i}from"./assets/vendor-BmSfSYqi.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const b="52265753-7181a70cf6dcebc2c39de477c",L="/api/",w=15;u.defaults.baseURL="https://pixabay.com";async function f(e,o=1){return(await u.get(L,{params:{key:b,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:w}})).data}let c=null;function p(e){const o=document.querySelector(".gallery"),s=e.map(n=>`<li class="gallery-item">
         <div><a href="${n.largeImageURL}">
         <img class="gallery-img" src="${n.webformatURL}" alt="${n.tags}" />
         </a>
         <div class="img-info">
          <div class="info-block"><p>Likes</p><p>${n.likes}</p></div>
          <div class="info-block"><p>Views</p><p>${n.views}</p></div>
          <div class="info-block"><p>Comments</p><p>${n.comments}</p></div>
          <div class="info-block"><p>Downloads</p><p>${n.downloads}</p></div>
        </div>
      </div>
      </li>`).join("");o.insertAdjacentHTML("beforeend",s),c?c.refresh():c=new v(".gallery a")}function E(){const e=document.querySelector(".gallery");e.innerHTML=""}function y(){const e=document.querySelector(".loader");e.style.display="block"}function m(){const e=document.querySelector(".loader");e.style.display="none"}function R(){const e=document.querySelector(".moreBtn");e.style.display="block"}function h(){const e=document.querySelector(".moreBtn");e.style.display="none"}function q(){const e=document.querySelector(".gallery-item");if(e){const o=e.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}const S=document.querySelector("form"),P=document.querySelector(".moreBtn");let d="",a=1;const g=15;S.addEventListener("submit",async e=>{e.preventDefault();const o=e.currentTarget.elements["search-text"].value.trim();if(!o){i.error({title:"error",message:"Please enter a word to search for.",position:"topRight"});return}d=o,a=1,E(),h(),y();try{const s=await f(d,a);if(s.hits.length===0){i.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"red"});return}p(s.hits),s.totalHits>g?R():i.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(s){console.error("error:",s),i.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",color:"red"})}finally{m()}});P.addEventListener("click",async()=>{a+=1,y();try{const e=await f(d,a);p(e.hits),q(),a*g>=e.totalHits&&(h(),i.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(e){console.error("Load more error:",e),i.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{m()}});
//# sourceMappingURL=index.js.map
